### ISSUE TITLE
Quick Start Guide?

### ISSUE THREAD

**Issue by neogeek83** [hkparker/Wave#1]
I wanted to take Wave for a spin, how do get it up and running? Just looking for the series of commands I'd need to run post cloning the repo.

**Comment by hkparker** [comment]
Hey!  Thanks for opening a ticket.

Getting a building section on the readme is near the top of the todo list, but there's not a whole lot to see yet as I'm still getting off the ground.

Right now you can use a collector to sniff 802.11 frames, but I've only started parsing the options fields on probe requests so far.  Those get streamed up through a web socket to Wave where they are stored in elasticsearch for 30 seconds.  But there are no IDS rules looking at that data yet.  Testing framework is setup, but no tests yet.  I have a basic bootstrap nav setup and theme done with react and webpack, but there's no visualization yet (or communication of any kind really).  It looks like this:

![screenshot from 2016-01-31 22-49-06](https://cloud.githubusercontent.com/assets/2918615/12710627/643be760-c86d-11e5-9f56-9d59d3d30cb2.png)

So, lots going on, but still pretty early, check back in a few weeks.  I'll close this once I start maintaining a building section on the readme.

**Comment by hkparker** [comment]
Hey again.  Been busy with work and [go-i2p](https://github.com/hkparker/go-i2p) but starting to get back around to this.  Happy to say the information on the README should get you setup with a dev environment now.  Please let me know if you have any trouble!
